FROM balenalib/raspberrypi3-node:buster-build

RUN [ "cross-build-start" ]
RUN install_packages \
  python3-dev \
  python3-pip \
  youtube-dl \
  lame \
  mpg321 \
  mplayer \
  livestreamer \
  curl \
  git

# GET PICAST NEEDED FILES...
WORKDIR /usr/src/app

# GET OMXIV
RUN git clone https://github.com/b23prodtm/omxiv.git

COPY package-lock.json .
COPY package.json .

RUN echo "Node install dependencies" \
  && npm install

RUN [ "cross-build-end" ]

COPY index index
COPY picast.js .

RUN echo "Welcome to PiCAST 3! \n\n\n"

CMD [ "/bin/bash", "node picast.js" ]
EXPOSE 3000
