FROM balenalib/%%BALENA_MACHINE_NAME%%-node:buster-build

# RUN [ "cross-build-start" ]
RUN install_packages \
  python-dev \
  python-pip \
  youtube-dl \
  lame \
  mpg321 \
  mplayer \
  livestreamer \
  git \
  curl

WORKDIR /usr/src
COPY . .

# H264 Process...
WORKDIR /usr/src/x264
RUN ./configure --host=arm-unknown-linux-gnueabi --enable-static --disable-opencl \
  && sudo make \
  && sudo make install

# Process for FFMPEG...
WORKDIR /usr/src/ffmpeg
RUN ./configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree \
  && make \
  && make install

# GET PICAST NEEDED FILES...
WORKDIR /usr/src

RUN echo "Node install dependencies" \
  && npm install

# RUN [ "cross-build-end" ]

RUN echo "Welcome to PiCAST 3! \n\n\n"

CMD [ "/bin/bash", "node picast.js" ]
EXPOSE 3000 80
