version: '2'
services:
  picast:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.template
    image: betothreeprod/picast-%%BALENA_MACHINE_NAME%%
    ports:
      - "3000:3000"
  omxiv:
    network_mode: host
    restart: always
    build:
      context: ./omxiv
      dockerfile: Dockerfile.template
    image: betothreeprod/omxiv
  wifi-connect:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.template
    image: betothreeprod/python-wifi-connect-%%BALENA_MACHINE_NAME%%
    env_file: common.env
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    privileged: true
    ports:
      - "80:80"
